; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[project]
name = imu-based-human-activity-classification

[env:nucleo_l476rg]
platform = ststm32
framework = stm32cube
board = nucleo_l476rg

monitor_speed = 115200
; Let PlatformIO auto-detect the USB port on macOS
; monitor_port = //dev/ttyACM1

build_flags=
    ; The tensorflowlite-micro library paths
    -Ilib/tflm_tree
    -Ilib/tflm_tree/tensorflow
    -Ilib/tflm_tree/tensorflow/lite
    -Ilib/tflm_tree/tensorflow/lite/micro
    
    ; The tensorflowlite-micro third path library paths
    -Ilib/tflm_tree/third_party/flatbuffers/include
    -Ilib/tflm_tree/third_party/gemmlowp
    -Ilib/tflm_tree/third_party/kissfft
    -Ilib/tflm_tree/third_party/ruy

    ; Required to exclude standard array allocation not available for cortex-m4
    -DTF_LITE_STATIC_MEMORY
    -DNUCLEO_L476RG

    ; The tflm build uses c++17 standard
    -std=c++17

    ; Force inclusion of floating-point support in printf (e.g., %f) 
    -Wl,-u,_printf_float