; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[project]
name = imu-based-human-activity-classification

[env:nucleo_l476rg]
platform = ststm32
framework = stm32cube
board = nucleo_l476rg

monitor_speed = 115200
; Let PlatformIO auto-detect the USB port on macOS
; monitor_port = //dev/ttyACM1

build_flags =
    ; Core Project Path Includes (Forces visibility between folders)
    -I include
    -I src

    ; Core TensorFlow Lite Micro Engine Paths
    -I lib/tflm_tree
    -I lib/tflm_tree/tensorflow
    -I lib/tflm_tree/tensorflow/lite
    -I lib/tflm_tree/tensorflow/lite/micro
    
    ; Embedded Math Extensions & Third Party Subtrees
    -I lib/tflm_tree/third_party/flatbuffers/include
    -I lib/tflm_tree/third_party/gemmlowp
    -I lib/tflm_tree/third_party/kissfft
    -I lib/tflm_tree/third_party/ruy

    ; Exclude standard array allocation not available for cortex-m4
    -D TF_LITE_STATIC_MEMORY
    -D NUCLEO_L476RG

    ; Modern TFLM compilation requires the C++17 standard
    -std=c++17

    ; Force inclusion of floating-point support in serial prints
    -Wl,-u,_printf_float